services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/usr/share/postgres/data
    ports:
      - "5432:5432"


  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"


volumes:
  postgres_data:
    driver: local